import type { Course, CourseModule } from '@/lib/service/course';

const defaultModules: CourseModule[] = [
    {
        id: 'module-1',
        title: 'Foundations',
        description: 'Build core skills with guided practice',
        lessons: [
            {
                id: 'lesson-1',
                title: 'Core Concepts',
                type: 'video',
                duration: '18 min',
                completed: false,
            },
            {
                id: 'lesson-2',
                title: 'Hands-on Exercise',
                type: 'exercise',
                duration: '30 min',
                completed: false,
            },
        ],
    },
    {
        id: 'module-2',
        title: 'Applied Skills',
        description: 'Turn knowledge into real-world outcomes',
        lessons: [
            {
                id: 'lesson-3',
                title: 'Mini Project',
                type: 'project',
                duration: '60 min',
                completed: false,
            },
            {
                id: 'lesson-4',
                title: 'Best Practices',
                type: 'video',
                duration: '22 min',
                completed: false,
            },
        ],
    },
];

export const courses: Course[] = [
    {
        id: '1',
        title: 'Advanced React & Next.js Mastery',
        category: 'Web Development',
        description:
            'Build modern, scalable web applications with React 19 and Next.js 16. Learn from industry experts and master the latest patterns, performance optimization, and real-world best practices.',
        rating: 5,
        ratingCount: 2847,
        instructor: 'Sarah Chen',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '32 hours of content',
        level: 'Advanced',
        students: 12340,
        price: '$99.99',
        image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
        modules: [
            {
                id: 'module-1',
                title: 'React Fundamentals & Hooks',
                description: 'Master the basics of React and modern hooks',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Introduction to React 19',
                        type: 'video',
                        duration: '15 min',
                        completed: true,
                    },
                    {
                        id: 'lesson-2',
                        title: 'JSX and Components',
                        type: 'video',
                        duration: '20 min',
                        completed: true,
                    },
                    {
                        id: 'lesson-3',
                        title: 'Hooks Deep Dive',
                        type: 'exercise',
                        duration: '30 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-4',
                        title: 'Custom Hooks',
                        type: 'exercise',
                        duration: '25 min',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-2',
                title: 'Next.js 16 Advanced Features',
                description:
                    'Explore Server Components, App Router, and optimization',
                lessons: [
                    {
                        id: 'lesson-5',
                        title: 'Server Components Introduction',
                        type: 'video',
                        duration: '18 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-6',
                        title: 'App Router Patterns',
                        type: 'video',
                        duration: '22 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-7',
                        title: 'Middleware & Auth',
                        type: 'exercise',
                        duration: '35 min',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-3',
                title: 'Performance & Optimization',
                description:
                    'Learn caching, rendering strategies, and performance metrics',
                lessons: [
                    {
                        id: 'lesson-8',
                        title: 'Image & Font Optimization',
                        type: 'video',
                        duration: '20 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-9',
                        title: 'Caching Strategies',
                        type: 'exercise',
                        duration: '40 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-10',
                        title: 'Real-world Performance Project',
                        type: 'project',
                        duration: '120 min',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-4',
                title: 'Full-Stack Project',
                description: 'Build a complete production-ready application',
                lessons: [
                    {
                        id: 'lesson-11',
                        title: 'Project Planning & Setup',
                        type: 'video',
                        duration: '25 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-12',
                        title: 'Database & API Integration',
                        type: 'exercise',
                        duration: '60 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-13',
                        title: 'Final Project Submission',
                        type: 'project',
                        duration: '180 min',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '2',
        title: 'Python for Data Science',
        category: 'Data Science',
        description:
            'Master Python programming for data analysis, visualization, and machine learning with hands-on projects.',
        rating: 5,
        ratingCount: 1924,
        instructor: 'Michael Rodriguez',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '40 hours of content',
        level: 'Intermediate',
        students: 8765,
        price: '$89.99',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        modules: [
            {
                id: 'module-1',
                title: 'Python Fundamentals',
                description: 'Learn Python basics and data structures',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Python Syntax & Variables',
                        type: 'video',
                        duration: '20 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Data Types & Collections',
                        type: 'exercise',
                        duration: '30 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-3',
                        title: 'Functions & Modules',
                        type: 'video',
                        duration: '25 min',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-2',
                title: 'Data Analysis with Pandas',
                description: 'Work with datasets and perform analysis',
                lessons: [
                    {
                        id: 'lesson-4',
                        title: 'DataFrames & Series',
                        type: 'video',
                        duration: '30 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-5',
                        title: 'Data Cleaning',
                        type: 'exercise',
                        duration: '45 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-6',
                        title: 'Analysis Project',
                        type: 'project',
                        duration: '120 min',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '3',
        title: 'Figma UI/UX Design Masterclass',
        category: 'Design',
        description:
            'Create stunning user experiences using Figma. Learn design principles, prototyping, and real-world workflows.',
        rating: 5,
        ratingCount: 1456,
        instructor: 'Emily Zhang',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '28 hours of content',
        level: 'Beginner',
        students: 6234,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?auto=format&fit=crop&w=1200&q=80',
        modules: [
            {
                id: 'module-1',
                title: 'Figma Essentials',
                description: 'Master Figma interface and tools',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Figma Interface Tour',
                        type: 'video',
                        duration: '25 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Components & Variants',
                        type: 'exercise',
                        duration: '40 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-3',
                        title: 'Prototyping Basics',
                        type: 'video',
                        duration: '20 min',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '4',
        title: 'Mobile App Development with React Native',
        category: 'Mobile',
        description:
            'Build cross-platform mobile apps with React Native. Deploy to iOS and Android from a single codebase.',
        rating: 5,
        ratingCount: 987,
        instructor: 'James Wilson',
        lastUpdated: 'November 2025',
        language: 'English',
        duration: '35 hours of content',
        level: 'Advanced',
        students: 4321,
        price: '$94.99',
        image: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?auto=format&fit=crop&w=1200&q=80',
        modules: [
            {
                id: 'module-1',
                title: 'React Native Fundamentals',
                description: 'Get started with React Native',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Setup & Environment',
                        type: 'video',
                        duration: '15 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Core Components',
                        type: 'exercise',
                        duration: '35 min',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '5',
        title: 'Web Development Mastery',
        category: 'Web Development',
        description:
            'Learn modern HTML, CSS, and JavaScript with projects that build confidence and real-world skills.',
        rating: 4.8,
        ratingCount: 1203,
        instructor: 'Alex Johnson',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '22 hours of content',
        level: 'Beginner',
        students: 12450,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '6',
        title: 'Data Science Fundamentals',
        category: 'Data Science',
        description:
            'Build a solid data science foundation covering statistics, Python, and machine learning workflows.',
        rating: 4.9,
        ratingCount: 856,
        instructor: 'Sarah Chen',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '26 hours of content',
        level: 'Beginner',
        students: 8920,
        price: '$89.99',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '7',
        title: 'Mobile App Development',
        category: 'Mobile',
        description:
            'Design, build, and ship mobile apps with best-practice UX and performance techniques.',
        rating: 4.7,
        ratingCount: 642,
        instructor: 'Mike Rodriguez',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '24 hours of content',
        level: 'Intermediate',
        students: 6780,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '8',
        title: 'UI/UX Design Principles',
        category: 'Design',
        description:
            'Learn the fundamentals of user-centered design, research, and prototyping for modern products.',
        rating: 4.9,
        ratingCount: 728,
        instructor: 'Emma Wilson',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '18 hours of content',
        level: 'Beginner',
        students: 5430,
        price: '$69.99',
        image: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '9',
        title: 'Advanced React Patterns',
        category: 'Web Development',
        description:
            'Level up your React skills with scalable patterns, performance tuning, and testing strategies.',
        rating: 4.8,
        ratingCount: 945,
        instructor: 'Alex Johnson',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '20 hours of content',
        level: 'Advanced',
        students: 9200,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '10',
        title: 'Python for Machine Learning',
        category: 'Data Science',
        description:
            'Apply Python to real ML problems with feature engineering, training, and model evaluation.',
        rating: 4.9,
        ratingCount: 723,
        instructor: 'Sarah Chen',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '30 hours of content',
        level: 'Intermediate',
        students: 7650,
        price: '$89.99',
        image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '11',
        title: 'React Native Mastery',
        category: 'Mobile',
        description:
            'Build polished cross-platform apps using React Native and a modern tooling stack.',
        rating: 4.7,
        ratingCount: 456,
        instructor: 'Mike Rodriguez',
        lastUpdated: 'November 2025',
        language: 'English',
        duration: '26 hours of content',
        level: 'Intermediate',
        students: 5120,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '12',
        title: 'Figma Design Systems',
        category: 'Design',
        description:
            'Create scalable design systems in Figma with tokens, components, and documentation.',
        rating: 4.8,
        ratingCount: 612,
        instructor: 'Emma Wilson',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '16 hours of content',
        level: 'Intermediate',
        students: 4890,
        price: '$69.99',
        image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '13',
        title: 'Full-Stack JavaScript',
        category: 'Web Development',
        description:
            'Build complete web apps using Node.js, databases, and modern frontend frameworks.',
        rating: 4.8,
        ratingCount: 1087,
        instructor: 'Alex Johnson',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '34 hours of content',
        level: 'Beginner',
        students: 10230,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '14',
        title: 'Deep Learning Specialization',
        category: 'Data Science',
        description:
            'Dive into deep learning with neural networks, tuning, and real-world applications.',
        rating: 4.9,
        ratingCount: 534,
        instructor: 'Sarah Chen',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '36 hours of content',
        level: 'Advanced',
        students: 6540,
        price: '$99.99',
        image: 'https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '15',
        title: 'iOS Development with Swift',
        category: 'Mobile',
        description:
            'Learn Swift fundamentals and build iOS apps that feel fast and native.',
        rating: 4.7,
        ratingCount: 389,
        instructor: 'Mike Rodriguez',
        lastUpdated: 'November 2025',
        language: 'English',
        duration: '28 hours of content',
        level: 'Intermediate',
        students: 4320,
        price: '$84.99',
        image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '16',
        title: 'Web Design Essentials',
        category: 'Design',
        description:
            'Learn layout, typography, and responsive design essentials for modern web experiences.',
        rating: 4.9,
        ratingCount: 876,
        instructor: 'Emma Wilson',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '20 hours of content',
        level: 'Beginner',
        students: 8765,
        price: '$69.99',
        image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '17',
        title: 'Node.js API Engineering',
        category: 'Web Development',
        description:
            'Build secure, scalable APIs with Node.js, authentication, and testing strategies.',
        rating: 4.7,
        ratingCount: 512,
        instructor: 'Jordan Lee',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '18 hours of content',
        level: 'Intermediate',
        students: 7340,
        price: '$84.99',
        image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '18',
        title: 'Data Visualization with D3',
        category: 'Data Science',
        description:
            'Turn data into compelling stories with D3.js, charts, and interaction patterns.',
        rating: 4.6,
        ratingCount: 367,
        instructor: 'Priya Patel',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '16 hours of content',
        level: 'Intermediate',
        students: 4980,
        price: '$74.99',
        image: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '19',
        title: 'Android Development with Kotlin',
        category: 'Mobile',
        description:
            'Ship Android apps with Kotlin, Jetpack components, and modern architecture patterns.',
        rating: 4.8,
        ratingCount: 441,
        instructor: 'Diego Torres',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '26 hours of content',
        level: 'Beginner',
        students: 5890,
        price: '$84.99',
        image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '20',
        title: 'Product Design Workshop',
        category: 'Design',
        description:
            'Design end-to-end product experiences with research, flows, and high-fidelity prototypes.',
        rating: 4.7,
        ratingCount: 305,
        instructor: 'Avery Kim',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '14 hours of content',
        level: 'Intermediate',
        students: 4020,
        price: '$72.99',
        image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '21',
        title: 'TypeScript for Professionals',
        category: 'Web Development',
        description:
            'Master TypeScript with advanced types, architecture patterns, and migration strategies.',
        rating: 4.8,
        ratingCount: 690,
        instructor: 'Morgan Reed',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '22 hours of content',
        level: 'Advanced',
        students: 8150,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '22',
        title: 'AI for Product Teams',
        category: 'Data Science',
        description:
            'Understand AI fundamentals and apply them to product strategy and delivery.',
        rating: 4.6,
        ratingCount: 274,
        instructor: 'Noah Brooks',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '12 hours of content',
        level: 'Beginner',
        students: 3650,
        price: '$94.99',
        image: 'https://images.unsplash.com/photo-1526378722370-4e7d8a0a8d3b?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
];

export const categories = [
    'All',
    'Web Development',
    'Data Science',
    'Mobile',
    'Design',
];

export const levels = ['All', 'Beginner', 'Intermediate', 'Advanced'];

export function getCourseById(id: string) {
    return courses.find((course) => course.id === id);
}

export function getCoursesByCategory(category: string) {
    return courses.filter((course) => course.category === category);
}
