import type { Course, CourseModule } from '@/lib/service/course';
import { CourseSyllabusResponse } from '@/lib/service/syllabus/type';

const defaultModules: CourseModule[] = [
    {
        id: 'module-1',
        title: 'Foundations',
        description: 'Build core skills with guided practice',
        lessons: [
            {
                id: 'lesson-1',
                title: 'Core Concepts',
                type: 'video',
                duration: '18 min',
                completed: false,
            },
            {
                id: 'lesson-2',
                title: 'Hands-on Exercise',
                type: 'exercise',
                duration: '30 min',
                completed: false,
            },
        ],
    },
    {
        id: 'module-2',
        title: 'Applied Skills',
        description: 'Turn knowledge into real-world outcomes',
        lessons: [
            {
                id: 'lesson-3',
                title: 'Mini Project',
                type: 'project',
                duration: '60 min',
                completed: false,
            },
            {
                id: 'lesson-4',
                title: 'Best Practices',
                type: 'video',
                duration: '22 min',
                completed: false,
            },
        ],
    },
];

export const courses: Course[] = [
    {
        id: '1',
        title: 'Advanced React & Next.js Mastery',
        category: 'Web Development',
        description:
            'Build modern, scalable web applications with React 19 and Next.js 16. Learn from industry experts and master the latest patterns, performance optimization, and real-world best practices.',
        rating: 5,
        ratingCount: 2847,
        instructor: 'Sarah Chen',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '32 hours of content',
        level: 'Advanced',
        students: 12340,
        price: '$99.99',
        image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
        modules: [
            {
                id: 'module-1',
                title: 'React Fundamentals & Hooks',
                description: 'Master the basics of React and modern hooks',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Introduction to React 19',
                        type: 'video',
                        duration: '15 min',
                        completed: true,
                    },
                    {
                        id: 'lesson-2',
                        title: 'JSX and Components',
                        type: 'video',
                        duration: '20 min',
                        completed: true,
                    },
                    {
                        id: 'lesson-3',
                        title: 'Hooks Deep Dive',
                        type: 'exercise',
                        duration: '30 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-4',
                        title: 'Custom Hooks',
                        type: 'exercise',
                        duration: '25 min',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-2',
                title: 'Next.js 16 Advanced Features',
                description:
                    'Explore Server Components, App Router, and optimization',
                lessons: [
                    {
                        id: 'lesson-5',
                        title: 'Server Components Introduction',
                        type: 'video',
                        duration: '18 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-6',
                        title: 'App Router Patterns',
                        type: 'video',
                        duration: '22 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-7',
                        title: 'Middleware & Auth',
                        type: 'exercise',
                        duration: '35 min',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-3',
                title: 'Performance & Optimization',
                description:
                    'Learn caching, rendering strategies, and performance metrics',
                lessons: [
                    {
                        id: 'lesson-8',
                        title: 'Image & Font Optimization',
                        type: 'video',
                        duration: '20 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-9',
                        title: 'Caching Strategies',
                        type: 'exercise',
                        duration: '40 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-10',
                        title: 'Real-world Performance Project',
                        type: 'project',
                        duration: '120 min',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-4',
                title: 'Full-Stack Project',
                description: 'Build a complete production-ready application',
                lessons: [
                    {
                        id: 'lesson-11',
                        title: 'Project Planning & Setup',
                        type: 'video',
                        duration: '25 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-12',
                        title: 'Database & API Integration',
                        type: 'exercise',
                        duration: '60 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-13',
                        title: 'Final Project Submission',
                        type: 'project',
                        duration: '180 min',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '2',
        title: 'Python for Data Science',
        category: 'Data Science',
        description:
            'Master Python programming for data analysis, visualization, and machine learning with hands-on projects.',
        rating: 5,
        ratingCount: 1924,
        instructor: 'Michael Rodriguez',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '40 hours of content',
        level: 'Intermediate',
        students: 8765,
        price: '$89.99',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        modules: [
            {
                id: 'module-1',
                title: 'Python Fundamentals',
                description: 'Learn Python basics and data structures',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Python Syntax & Variables',
                        type: 'video',
                        duration: '20 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Data Types & Collections',
                        type: 'exercise',
                        duration: '30 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-3',
                        title: 'Functions & Modules',
                        type: 'video',
                        duration: '25 min',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-2',
                title: 'Data Analysis with Pandas',
                description: 'Work with datasets and perform analysis',
                lessons: [
                    {
                        id: 'lesson-4',
                        title: 'DataFrames & Series',
                        type: 'video',
                        duration: '30 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-5',
                        title: 'Data Cleaning',
                        type: 'exercise',
                        duration: '45 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-6',
                        title: 'Analysis Project',
                        type: 'project',
                        duration: '120 min',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '3',
        title: 'Figma UI/UX Design Masterclass',
        category: 'Design',
        description:
            'Create stunning user experiences using Figma. Learn design principles, prototyping, and real-world workflows.',
        rating: 5,
        ratingCount: 1456,
        instructor: 'Emily Zhang',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '28 hours of content',
        level: 'Beginner',
        students: 6234,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?auto=format&fit=crop&w=1200&q=80',
        modules: [
            {
                id: 'module-1',
                title: 'Figma Essentials',
                description: 'Master Figma interface and tools',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Figma Interface Tour',
                        type: 'video',
                        duration: '25 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Components & Variants',
                        type: 'exercise',
                        duration: '40 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-3',
                        title: 'Prototyping Basics',
                        type: 'video',
                        duration: '20 min',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '4',
        title: 'Mobile App Development with React Native',
        category: 'Mobile',
        description:
            'Build cross-platform mobile apps with React Native. Deploy to iOS and Android from a single codebase.',
        rating: 5,
        ratingCount: 987,
        instructor: 'James Wilson',
        lastUpdated: 'November 2025',
        language: 'English',
        duration: '35 hours of content',
        level: 'Advanced',
        students: 4321,
        price: '$94.99',
        image: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?auto=format&fit=crop&w=1200&q=80',
        modules: [
            {
                id: 'module-1',
                title: 'React Native Fundamentals',
                description: 'Get started with React Native',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Setup & Environment',
                        type: 'video',
                        duration: '15 min',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Core Components',
                        type: 'exercise',
                        duration: '35 min',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '5',
        title: 'Web Development Mastery',
        category: 'Web Development',
        description:
            'Learn modern HTML, CSS, and JavaScript with projects that build confidence and real-world skills.',
        rating: 4.8,
        ratingCount: 1203,
        instructor: 'Alex Johnson',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '22 hours of content',
        level: 'Beginner',
        students: 12450,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '6',
        title: 'Data Science Fundamentals',
        category: 'Data Science',
        description:
            'Build a solid data science foundation covering statistics, Python, and machine learning workflows.',
        rating: 4.9,
        ratingCount: 856,
        instructor: 'Sarah Chen',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '26 hours of content',
        level: 'Beginner',
        students: 8920,
        price: '$89.99',
        image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '7',
        title: 'Mobile App Development',
        category: 'Mobile',
        description:
            'Design, build, and ship mobile apps with best-practice UX and performance techniques.',
        rating: 4.7,
        ratingCount: 642,
        instructor: 'Mike Rodriguez',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '24 hours of content',
        level: 'Intermediate',
        students: 6780,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '8',
        title: 'UI/UX Design Principles',
        category: 'Design',
        description:
            'Learn the fundamentals of user-centered design, research, and prototyping for modern products.',
        rating: 4.9,
        ratingCount: 728,
        instructor: 'Emma Wilson',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '18 hours of content',
        level: 'Beginner',
        students: 5430,
        price: '$69.99',
        image: 'https://images.unsplash.com/photo-1545239351-ef35f43d514b?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '9',
        title: 'Advanced React Patterns',
        category: 'Web Development',
        description:
            'Level up your React skills with scalable patterns, performance tuning, and testing strategies.',
        rating: 4.8,
        ratingCount: 945,
        instructor: 'Alex Johnson',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '20 hours of content',
        level: 'Advanced',
        students: 9200,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '10',
        title: 'Python for Machine Learning',
        category: 'Data Science',
        description:
            'Apply Python to real ML problems with feature engineering, training, and model evaluation.',
        rating: 4.9,
        ratingCount: 723,
        instructor: 'Sarah Chen',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '30 hours of content',
        level: 'Intermediate',
        students: 7650,
        price: '$89.99',
        image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '11',
        title: 'React Native Mastery',
        category: 'Mobile',
        description:
            'Build polished cross-platform apps using React Native and a modern tooling stack.',
        rating: 4.7,
        ratingCount: 456,
        instructor: 'Mike Rodriguez',
        lastUpdated: 'November 2025',
        language: 'English',
        duration: '26 hours of content',
        level: 'Intermediate',
        students: 5120,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '12',
        title: 'Figma Design Systems',
        category: 'Design',
        description:
            'Create scalable design systems in Figma with tokens, components, and documentation.',
        rating: 4.8,
        ratingCount: 612,
        instructor: 'Emma Wilson',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '16 hours of content',
        level: 'Intermediate',
        students: 4890,
        price: '$69.99',
        image: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '13',
        title: 'Full-Stack JavaScript',
        category: 'Web Development',
        description:
            'Build complete web apps using Node.js, databases, and modern frontend frameworks.',
        rating: 4.8,
        ratingCount: 1087,
        instructor: 'Alex Johnson',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '34 hours of content',
        level: 'Beginner',
        students: 10230,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '14',
        title: 'Deep Learning Specialization',
        category: 'Data Science',
        description:
            'Dive into deep learning with neural networks, tuning, and real-world applications.',
        rating: 4.9,
        ratingCount: 534,
        instructor: 'Sarah Chen',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '36 hours of content',
        level: 'Advanced',
        students: 6540,
        price: '$99.99',
        image: 'https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '15',
        title: 'iOS Development with Swift',
        category: 'Mobile',
        description:
            'Learn Swift fundamentals and build iOS apps that feel fast and native.',
        rating: 4.7,
        ratingCount: 389,
        instructor: 'Mike Rodriguez',
        lastUpdated: 'November 2025',
        language: 'English',
        duration: '28 hours of content',
        level: 'Intermediate',
        students: 4320,
        price: '$84.99',
        image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '16',
        title: 'Web Design Essentials',
        category: 'Design',
        description:
            'Learn layout, typography, and responsive design essentials for modern web experiences.',
        rating: 4.9,
        ratingCount: 876,
        instructor: 'Emma Wilson',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '20 hours of content',
        level: 'Beginner',
        students: 8765,
        price: '$69.99',
        image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '17',
        title: 'Node.js API Engineering',
        category: 'Web Development',
        description:
            'Build secure, scalable APIs with Node.js, authentication, and testing strategies.',
        rating: 4.7,
        ratingCount: 512,
        instructor: 'Jordan Lee',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '18 hours of content',
        level: 'Intermediate',
        students: 7340,
        price: '$84.99',
        image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '18',
        title: 'Data Visualization with D3',
        category: 'Data Science',
        description:
            'Turn data into compelling stories with D3.js, charts, and interaction patterns.',
        rating: 4.6,
        ratingCount: 367,
        instructor: 'Priya Patel',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '16 hours of content',
        level: 'Intermediate',
        students: 4980,
        price: '$74.99',
        image: 'https://images.unsplash.com/photo-1545239351-1141bd82e8a6?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '19',
        title: 'Android Development with Kotlin',
        category: 'Mobile',
        description:
            'Ship Android apps with Kotlin, Jetpack components, and modern architecture patterns.',
        rating: 4.8,
        ratingCount: 441,
        instructor: 'Diego Torres',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '26 hours of content',
        level: 'Beginner',
        students: 5890,
        price: '$84.99',
        image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '20',
        title: 'Product Design Workshop',
        category: 'Design',
        description:
            'Design end-to-end product experiences with research, flows, and high-fidelity prototypes.',
        rating: 4.7,
        ratingCount: 305,
        instructor: 'Avery Kim',
        lastUpdated: 'December 2025',
        language: 'English',
        duration: '14 hours of content',
        level: 'Intermediate',
        students: 4020,
        price: '$72.99',
        image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '21',
        title: 'TypeScript for Professionals',
        category: 'Web Development',
        description:
            'Master TypeScript with advanced types, architecture patterns, and migration strategies.',
        rating: 4.8,
        ratingCount: 690,
        instructor: 'Morgan Reed',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '22 hours of content',
        level: 'Advanced',
        students: 8150,
        price: '$79.99',
        image: 'https://images.unsplash.com/photo-1517433456452-f9633a875f6f?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
    {
        id: '22',
        title: 'AI for Product Teams',
        category: 'Data Science',
        description:
            'Understand AI fundamentals and apply them to product strategy and delivery.',
        rating: 4.6,
        ratingCount: 274,
        instructor: 'Noah Brooks',
        lastUpdated: 'January 2026',
        language: 'English',
        duration: '12 hours of content',
        level: 'Beginner',
        students: 3650,
        price: '$94.99',
        image: 'https://images.unsplash.com/photo-1526378722370-4e7d8a0a8d3b?auto=format&fit=crop&w=1200&q=80',
        modules: defaultModules,
    },
];

export const categories = [
    'All',
    'Web Development',
    'Data Science',
    'Mobile',
    'Design',
];

export const levels = ['All', 'Beginner', 'Intermediate', 'Advanced'];

export function getCourseById(id: string) {
    return courses.find((course) => course.id === id);
}

export function getCoursesByCategory(category: string) {
    return courses.filter((course) => course.category === category);
}

export const learningPaths = [
    {
        id: '1',
        title: 'Full-Stack Web Developer',
        category: 'Web Development',
        description:
            'Master modern web development from frontend to backend. Learn React, Node.js, databases, and deployment to build production-ready applications.',
        level: 'Beginner → Advanced',
        duration: '120+ hours',
        students: 24500,
        progress: 45,
        modules: [
            {
                id: 'module-1',
                title: 'Frontend Foundations',
                description: 'Master HTML, CSS, and JavaScript',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'HTML & CSS Fundamentals',
                        type: 'video' as const,
                        duration: '10 hours',
                        completed: true,
                    },
                    {
                        id: 'lesson-2',
                        title: 'JavaScript Essentials',
                        type: 'video' as const,
                        duration: '12 hours',
                        completed: true,
                    },
                    {
                        id: 'lesson-3',
                        title: 'DOM Manipulation',
                        type: 'exercise' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-2',
                title: 'React Deep Dive',
                description: 'Advanced React patterns and hooks',
                lessons: [
                    {
                        id: 'lesson-4',
                        title: 'React Fundamentals',
                        type: 'video' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-5',
                        title: 'Advanced Hooks',
                        type: 'exercise' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-6',
                        title: 'State Management',
                        type: 'exercise' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-3',
                title: 'Backend Development',
                description: 'Node.js, Express, and API design',
                lessons: [
                    {
                        id: 'lesson-7',
                        title: 'Node.js Basics',
                        type: 'video' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-8',
                        title: 'Express.js & APIs',
                        type: 'exercise' as const,
                        duration: '12 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-9',
                        title: 'RESTful Design',
                        type: 'video' as const,
                        duration: '6 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-4',
                title: 'Database & Deployment',
                description: 'PostgreSQL, MongoDB, and cloud deployment',
                lessons: [
                    {
                        id: 'lesson-10',
                        title: 'PostgreSQL Fundamentals',
                        type: 'video' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-11',
                        title: 'Database Design',
                        type: 'exercise' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-12',
                        title: 'Deployment & DevOps',
                        type: 'exercise' as const,
                        duration: '12 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-5',
                title: 'Capstone Project',
                description: 'Build a complete full-stack application',
                lessons: [
                    {
                        id: 'lesson-13',
                        title: 'Project Planning',
                        type: 'video' as const,
                        duration: '6 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-14',
                        title: 'Development Sprint',
                        type: 'project' as const,
                        duration: '40 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-15',
                        title: 'Production Deployment',
                        type: 'project' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '2',
        title: 'Data Science & Analytics',
        category: 'Data Science',
        description:
            'Learn Python, data analysis, visualization, and machine learning to extract insights from data and build predictive models.',
        level: 'Beginner → Advanced',
        duration: '140+ hours',
        students: 18900,
        progress: 0,
        modules: [
            {
                id: 'module-1',
                title: 'Python Fundamentals',
                description: 'Python programming basics',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Python Syntax',
                        type: 'video' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Data Structures',
                        type: 'exercise' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-2',
                title: 'Data Analysis with Pandas',
                description: 'Work with datasets efficiently',
                lessons: [
                    {
                        id: 'lesson-3',
                        title: 'Pandas Basics',
                        type: 'video' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-4',
                        title: 'Data Cleaning',
                        type: 'exercise' as const,
                        duration: '12 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-5',
                        title: 'Data Exploration',
                        type: 'exercise' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-3',
                title: 'Data Visualization',
                description: 'Create compelling visualizations',
                lessons: [
                    {
                        id: 'lesson-6',
                        title: 'Matplotlib & Seaborn',
                        type: 'video' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-7',
                        title: 'Advanced Visualizations',
                        type: 'exercise' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-4',
                title: 'Machine Learning',
                description: 'Build predictive models',
                lessons: [
                    {
                        id: 'lesson-8',
                        title: 'ML Fundamentals',
                        type: 'video' as const,
                        duration: '12 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-9',
                        title: 'Supervised Learning',
                        type: 'exercise' as const,
                        duration: '15 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-10',
                        title: 'Unsupervised Learning',
                        type: 'exercise' as const,
                        duration: '12 hours',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '3',
        title: 'UI/UX Design Fundamentals',
        category: 'Design',
        description:
            'Create beautiful, user-centered digital experiences. Learn design principles, tools, and workflows used by leading companies.',
        level: 'Beginner → Intermediate',
        duration: '90+ hours',
        students: 16200,
        progress: 0,
        modules: [
            {
                id: 'module-1',
                title: 'Design Principles',
                description: 'Fundamentals of good design',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Design Fundamentals',
                        type: 'video' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Color & Typography',
                        type: 'exercise' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-2',
                title: 'Figma Mastery',
                description: 'Master design tools',
                lessons: [
                    {
                        id: 'lesson-3',
                        title: 'Figma Basics',
                        type: 'video' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-4',
                        title: 'Components & Systems',
                        type: 'exercise' as const,
                        duration: '12 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-3',
                title: 'User Research',
                description: 'Understand your users',
                lessons: [
                    {
                        id: 'lesson-5',
                        title: 'Research Methods',
                        type: 'video' as const,
                        duration: '6 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-6',
                        title: 'User Testing',
                        type: 'exercise' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                ],
            },
        ],
    },
    {
        id: '4',
        title: 'Mobile App Development',
        category: 'Mobile',
        description:
            'Build cross-platform mobile applications with React Native and Expo. Deploy to iOS and Android platforms.',
        level: 'Intermediate → Advanced',
        duration: '110+ hours',
        students: 14300,
        progress: 0,
        modules: [
            {
                id: 'module-1',
                title: 'React Native Basics',
                description: 'Get started with React Native',
                lessons: [
                    {
                        id: 'lesson-1',
                        title: 'Setup & Environment',
                        type: 'video' as const,
                        duration: '4 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-2',
                        title: 'Core Components',
                        type: 'exercise' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                ],
            },
            {
                id: 'module-2',
                title: 'Navigation & State',
                description: 'App architecture and navigation',
                lessons: [
                    {
                        id: 'lesson-3',
                        title: 'React Navigation',
                        type: 'video' as const,
                        duration: '8 hours',
                        completed: false,
                    },
                    {
                        id: 'lesson-4',
                        title: 'State Management',
                        type: 'exercise' as const,
                        duration: '10 hours',
                        completed: false,
                    },
                ],
            },
        ],
    },
];

export function getLearningPathById(id: string) {
    return learningPaths.find((path) => path.id === id);
}

export function getLearningPathsByCategory(category: string) {
    return learningPaths.filter((path) => path.category === category);
}

// course-syllabus-sample
export const mockStudentSyllabus: CourseSyllabusResponse = {
    course_id: 'course-1771579477259',
    course_title: 'Web dev 2026',
    modules: [
        {
            id: 'mod-1',
            course_id: 'course-1771579477259',
            title: 'Module 1: Fundamentals & Environment',
            sort_order: 1,
            lessons: [
                {
                    id: 'les-1-1',
                    module_id: 'mod-1',
                    title: '1.1. Welcome to the Platform',
                    sort_order: 1,
                    materials: [
                        {
                            id: 'mat-1',
                            lesson_id: 'les-1-1',
                            item_type: 'video',
                            title: 'Course Introduction',
                            sort_order: 1,
                            is_required: true,
                            is_preview: true,
                            is_completed: true,
                            duration: 15,
                        },
                        {
                            id: 'mat-2',
                            lesson_id: 'les-1-1',
                            item_type: 'file',
                            title: 'Course_Syllabus_2026',
                            sort_order: 2,
                            is_required: false,
                            is_preview: true,
                            is_completed: true,
                            file_type: 'pdf',
                        },
                    ],
                },
                {
                    id: 'les-1-2',
                    module_id: 'mod-1',
                    title: '1.2. Core Concepts Assessment',
                    sort_order: 2,
                    materials: [
                        {
                            id: 'mat-3',
                            lesson_id: 'les-1-2',
                            item_type: 'reading',
                            title: 'Pre-requisite Checklist',
                            sort_order: 1,
                            is_required: true,
                            is_preview: false,
                            is_completed: true,
                            duration: 5,
                        },
                        {
                            id: 'mat-4',
                            lesson_id: 'les-1-2',
                            item_type: 'quiz',
                            title: 'Initial Assessment Quiz',
                            sort_order: 2,
                            is_required: true,
                            is_preview: false,
                            is_completed: true,
                            duration: 20,
                        },
                    ],
                },
            ],
        },
        {
            id: 'mod-2',
            course_id: 'course-1771579477259',
            title: 'Module 2: Modern Frontend with Next.js',
            sort_order: 2,
            lessons: [
                {
                    id: 'les-2-1',
                    module_id: 'mod-2',
                    title: '2.1. Server Components & Routing',
                    sort_order: 1,
                    materials: [
                        {
                            id: 'mat-5',
                            lesson_id: 'les-2-1',
                            item_type: 'video',
                            title: 'App Router Deep Dive',
                            sort_order: 1,
                            is_required: true,
                            is_preview: false,
                            is_completed: true,
                            duration: 45,
                        },
                        {
                            id: 'mat-6',
                            lesson_id: 'les-2-1',
                            item_type: 'reading',
                            title: 'Client vs Server Components',
                            sort_order: 2,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 10,
                        },
                    ],
                },
                {
                    id: 'les-2-2',
                    module_id: 'mod-2',
                    title: '2.2. State Management & Forms',
                    sort_order: 2,
                    materials: [
                        {
                            id: 'mat-7',
                            lesson_id: 'les-2-2',
                            item_type: 'video',
                            title: 'Handling Complex Forms',
                            sort_order: 1,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 30,
                        },
                        {
                            id: 'mat-8',
                            lesson_id: 'les-2-2',
                            item_type: 'coding',
                            title: 'Build a Multi-step Form',
                            sort_order: 2,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            language: 'typescript',
                        },
                    ],
                },
            ],
        },
        {
            id: 'mod-3',
            course_id: 'course-1771579477259',
            title: 'Module 3: Robust Backend with Spring Boot',
            sort_order: 3,
            lessons: [
                {
                    id: 'les-3-1',
                    module_id: 'mod-3',
                    title: '3.1. API Architecture & Security',
                    sort_order: 1,
                    materials: [
                        {
                            id: 'mat-9',
                            lesson_id: 'les-3-1',
                            item_type: 'video',
                            title: 'RESTful Principles & JWT',
                            sort_order: 1,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 50,
                        },
                        {
                            id: 'mat-10',
                            lesson_id: 'les-3-1',
                            item_type: 'file',
                            title: 'API_Contract_Spec',
                            sort_order: 2,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            file_type: 'json',
                        },
                    ],
                },
                {
                    id: 'les-3-2',
                    module_id: 'mod-3',
                    title: '3.2. Data Persistence',
                    sort_order: 2,
                    materials: [
                        {
                            id: 'mat-11',
                            lesson_id: 'les-3-2',
                            item_type: 'reading',
                            title: 'JPA & Hibernate Optimization',
                            sort_order: 1,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 15,
                        },
                        {
                            id: 'mat-12',
                            lesson_id: 'les-3-2',
                            item_type: 'coding',
                            title: 'Implement User Repository',
                            sort_order: 2,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            language: 'java',
                        },
                        {
                            id: 'mat-13',
                            lesson_id: 'les-3-2',
                            item_type: 'quiz',
                            title: 'Database Relationship Check',
                            sort_order: 3,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 10,
                        },
                    ],
                },
            ],
        },
        {
            id: 'mod-4',
            course_id: 'course-1771579477259',
            title: 'Module 4: High Performance with Go',
            sort_order: 4,
            lessons: [
                {
                    id: 'les-4-1',
                    module_id: 'mod-4',
                    title: '4.1. Concurrency in Go',
                    sort_order: 1,
                    materials: [
                        {
                            id: 'mat-14',
                            lesson_id: 'les-4-1',
                            item_type: 'video',
                            title: 'Goroutines and Channels',
                            sort_order: 1,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 35,
                        },
                        {
                            id: 'mat-15',
                            lesson_id: 'les-4-1',
                            item_type: 'coding',
                            title: 'Worker Pool Implementation',
                            sort_order: 2,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            language: 'go',
                        },
                    ],
                },
            ],
        },
        {
            id: 'mod-5',
            course_id: 'course-1771579477259',
            title: 'Module 5: DevOps & Deployment',
            sort_order: 5,
            lessons: [
                {
                    id: 'les-5-1',
                    module_id: 'mod-5',
                    title: '5.1. Containerization & Pipelines',
                    sort_order: 1,
                    materials: [
                        {
                            id: 'mat-16',
                            lesson_id: 'les-5-1',
                            item_type: 'reading',
                            title: 'Dockerizing Fullstack Apps',
                            sort_order: 1,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 20,
                        },
                        {
                            id: 'mat-17',
                            lesson_id: 'les-5-1',
                            item_type: 'file',
                            title: 'docker-compose-template',
                            sort_order: 2,
                            is_required: false,
                            is_preview: false,
                            is_completed: false,
                            file_type: 'yaml',
                        },
                    ],
                },
                {
                    id: 'les-5-2',
                    module_id: 'mod-5',
                    title: '5.2. Zero Downtime Deployment',
                    sort_order: 2,
                    materials: [
                        {
                            id: 'mat-18',
                            lesson_id: 'les-5-2',
                            item_type: 'video',
                            title: 'Blue-Green Deployment Strategy',
                            sort_order: 1,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 40,
                        },
                        {
                            id: 'mat-19',
                            lesson_id: 'les-5-2',
                            item_type: 'quiz',
                            title: 'DevOps Final Exam',
                            sort_order: 2,
                            is_required: true,
                            is_preview: false,
                            is_completed: false,
                            duration: 30,
                        },
                    ],
                },
            ],
        },
    ],
};
